### ISSUE TITLE
Match dataset and document descriptions with API responses properties

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/wds-react-legacy#89]
## 💡 Description

See for data:
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/60993872/230444150-3df40fab-c5bb-4396-97c1-cc9826c83e66.png">

See for documents:
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/60993872/230444313-80f82c58-b8b5-4b1c-9146-b75e778dad26.png">

**Comment by tloubrieu-jpl** [comment]
@anilnatha is this ticket obsolete ?

**Comment by anilnatha** [comment]
@tloubrieu-jpl I think this ticket is obsolete because the design time has since revised the expanded state for all the result types shown in search. If there is still an issue with the content shown in the expanded state for any given item, let's create a new ticket to address it.  Closing this ticket.
